"""Semantic PII redaction replacing detected entities with structured placeholders."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence
import unicodedata

from privacygate.detection.names import NameRegistry
from privacygate.models import ContentBlock, Document, PIIEntity


@dataclass
class RedactionRecord:
    """Audit-safe record of an applied redaction, containing no raw PII."""

    block_id: str
    entity_type: str
    placeholder: str
    source_location: dict[str, int | str] = field(default_factory=dict)


PLACEHOLDER_MAP: dict[str, str] = {
    "EMAIL_ADDRESS": "EMAIL",
    "PHONE_NUMBER": "PHONE",
    "US_SSN": "GOVERNMENT_ID",
    "IBAN_CODE": "ACCOUNT_NUMBER",
    "CUSTOMER_REF": "CUSTOMER_ID",
}

SAFE_LOCATION_FIELDS = (
    "page_number", "slide_number", "paragraph_number", "body_index", "table_number",
    "row_number", "column_number", "shape_id", "shape_index", "block_order",
    "source_block_number", "source_paragraph_number", "source_line_number",
)


def _safe_source_location(location: dict[str, int | str]) -> dict[str, int]:
    """Keep only structural coordinates generated by extraction."""
    return {
        key: value for key in SAFE_LOCATION_FIELDS
        if type(value := location.get(key)) is int and value >= 0
    }


def get_placeholder(entity_type: str) -> str:
    """Return the standardized semantic placeholder for an entity type."""
    clean_type = entity_type.strip().upper()
    canonical_type = PLACEHOLDER_MAP.get(clean_type, clean_type)
    return f"[{canonical_type}]"


class PseudonymSession:
    """Temporary identity assignments for one pipeline run; never serialize."""

    __slots__ = ("_name_registry", "_tokens_by_identity", "_counters", "_issued_tokens")

    def __init__(self, name_registry: NameRegistry | None = None) -> None:
        self._name_registry = name_registry
        self._tokens_by_identity: dict[tuple[str, str, str | int], str] = {}
        self._counters: dict[str, int] = {}
        self._issued_tokens: set[str] = set()

    def __repr__(self) -> str:
        return f"PseudonymSession(issued={len(self._issued_tokens)})"

    @property
    def issued_tokens(self) -> frozenset[str]:
        """Only generated tokens leave the session for privacy validation."""
        return frozenset(self._issued_tokens)

    def placeholder_for(self, entity_type: str, value: str) -> str:
        canonical_type = get_placeholder(entity_type)[1:-1]
        normalized = unicodedata.normalize("NFC", value.strip())
        person_index = self._name_registry.resolve_person(normalized) if (
            canonical_type == "PERSON" and self._name_registry is not None
        ) else None
        if person_index is not None:
            identity: tuple[str, str, str | int] = (canonical_type, "registry", person_index)
        else:
            if canonical_type == "EMAIL" and "@" in normalized:
                local, domain = normalized.rsplit("@", 1)
                normalized = f"{local}@{domain.casefold()}"
            identity = (canonical_type, "literal", normalized)

        token = self._tokens_by_identity.get(identity)
        if token is None:
            number = self._counters.get(canonical_type, 0) + 1
            self._counters[canonical_type] = number
            token = f"[{canonical_type}_{number:03d}]"
            self._tokens_by_identity[identity] = token
            self._issued_tokens.add(token)
        return token


def redact_text(
    text: str, entities: Sequence[PIIEntity], session: PseudonymSession | None = None,
) -> tuple[str, list[RedactionRecord]]:
    """Redact entities from a text string in reverse offset order to maintain index integrity."""
    if not text or not entities:
        return text, []

    # Assign in source order, then splice from the end to preserve offsets.
    replacements = [
        (entity, session.placeholder_for(entity.entity_type, text[entity.start:entity.end])
         if session is not None else get_placeholder(entity.entity_type))
        for entity in sorted(entities, key=lambda e: (e.start, e.end))
        if 0 <= entity.start < entity.end <= len(text)
    ]

    sanitized = text
    records: list[RedactionRecord] = []

    for entity, placeholder in reversed(replacements):
        # Splice sanitized string
        sanitized = sanitized[:entity.start] + placeholder + sanitized[entity.end:]

        records.append(
            RedactionRecord(
                block_id=entity.block_id,
                entity_type=entity.entity_type,
                placeholder=placeholder,
                source_location=_safe_source_location(entity.source_location),
            )
        )

    # Return sanitized text and chronological records
    records.reverse()
    return sanitized, records


def redact_document(
    document: Document,
    entities: Sequence[PIIEntity],
    session: PseudonymSession | None = None,
) -> tuple[Document, list[RedactionRecord]]:
    """Generate a sanitized Document replacing all detected PII with semantic placeholders.

    The original document is not mutated. All structural metadata and coordinates are preserved.
    """
    # Group entities by block_id
    by_block: dict[str, list[PIIEntity]] = {}
    for entity in entities:
        by_block.setdefault(entity.block_id, []).append(entity)

    sanitized_blocks: list[ContentBlock] = []
    all_records: list[RedactionRecord] = []

    for block in document.blocks:
        block_entities = by_block.get(block.block_id, [])
        if block_entities:
            clean_text, records = redact_text(block.text, block_entities, session=session)
            all_records.extend(records)
        else:
            clean_text = block.text

        sanitized_blocks.append(
            ContentBlock(
                block_id=block.block_id,
                text=clean_text,
                page_number=block.page_number,
                slide_number=block.slide_number,
                paragraph_number=block.paragraph_number,
                extraction_method=block.extraction_method,
                metadata=dict(block.metadata),
            )
        )

    sanitized_metadata = dict(document.metadata)
    sanitized_metadata["redacted"] = True
    sanitized_metadata["redaction_count"] = len(all_records)

    sanitized_doc = Document(
        document_id=f"{document.document_id}_sanitized",
        filename=document.filename,
        file_type=document.file_type,
        metadata=sanitized_metadata,
        blocks=sanitized_blocks,
    )

    return sanitized_doc, all_records
